CREATE TABLE [dbo].[MST_Company] (
    [PK_CompanyId]         BIGINT         IDENTITY (1, 1) NOT NULL,
    [FK_CompanyId]         BIGINT         NULL,
    [CompanyName]          VARCHAR (500)  NULL,
    [ContactPerson]        NVARCHAR (50)  NULL,
    [Mobile]               NVARCHAR (50)  NULL,
    [CompanyPhoneNo]       NVARCHAR (50)  NULL,
    [Email]                NVARCHAR (200) NULL,
    [FK_CountryId]         BIGINT         NULL,
    [FK_StateId]           BIGINT         NULL,
    [FK_CityId]            BIGINT         NULL,
    [GSTNo]                NVARCHAR (50)  NULL,
    [PanNo]                NVARCHAR (50)  NULL,
    [CIN]                  NVARCHAR (50)  NULL,
    [CompanyLogo_Name]     NVARCHAR (200) NULL,
    [AlternateMobileNo]    NVARCHAR (50)  NULL,
    [AlternateEmailID]     NVARCHAR (200) NULL,
    [IsActive]             BIT            NOT NULL,
    [IsDeleted]            BIT            NULL,
    [CreatedBy]            BIGINT         NULL,
    [CreatedDateTime]      DATETIME       NULL,
    [UpdatedBy]            BIGINT         NULL,
    [UpdatedDateTime]      DATETIME       NULL,
    [DeletedBy]            BIGINT         NULL,
    [DeletedDateTime]      DATETIME       NULL,
    [Address]              NVARCHAR (500) NULL,
    [AddressSame]          NVARCHAR (500) NULL,
    [PinCode]              NVARCHAR (50)  NULL,
    [PinCode_Billing]      NVARCHAR (50)  NULL,
    [FK_CountryId_Billing] BIGINT         NULL,
    [FK_CityId_Billing]    BIGINT         NULL,
    [FK_StateId_Billing]   BIGINT         NULL,
    [logoClass]            NVARCHAR (50)  NULL,
    PRIMARY KEY CLUSTERED ([PK_CompanyId] ASC)
);

