CREATE TABLE [dbo].[MST_User] (
    [PK_UserId]                    BIGINT         IDENTITY (1, 1) NOT NULL,
    [UserName]                     NVARCHAR (100) NULL,
    [FK_CategoryId]                BIGINT         NULL,
    [FK_RoleId]                    BIGINT         NULL,
    [FK_CustomerId]                BIGINT         NULL,
    [FK_AccountId]                 BIGINT         NULL,
    [UserPassword]                 NVARCHAR (50)  NULL,
    [MobileNo]                     NVARCHAR (20)  NULL,
    [AlternateMobileNo]            NVARCHAR (20)  NULL,
    [EmailId]                      NVARCHAR (100) NULL,
    [AlternateEmailId]             NVARCHAR (100) NULL,
    [Gender]                       NVARCHAR (10)  NULL,
    [DateOfBirth]                  NVARCHAR (150) NULL,
    [UserAddress]                  NVARCHAR (500) NULL,
    [ZipCode]                      NVARCHAR (30)  NULL,
    [FK_CountryId]                 BIGINT         NULL,
    [FK_StateId]                   BIGINT         NULL,
    [FK_CityId]                    BIGINT         NULL,
    [IsActive]                     BIT            NULL,
    [IsDeleted]                    BIT            NULL,
    [CreatedBy]                    BIGINT         NULL,
    [CreatedDateTime]              DATETIME       NULL,
    [UpdatedBy]                    BIGINT         NULL,
    [UpdatedDateTime]              DATETIME       NULL,
    [DeletedBy]                    BIGINT         NULL,
    [DeletedDateTime]              DATETIME       NULL,
    [FirstName]                    NVARCHAR (100) NULL,
    [LastName]                     NVARCHAR (100) NULL,
    [FullName]                     NVARCHAR (250) NULL,
    [ShareBy]                      NVARCHAR (250) NULL,
    [FK_InstallerId]               BIGINT         NULL,
    [FK_DriverId]                  BIGINT         NULL,
    [AppRegId]                     VARCHAR (500)  NULL,
    [IMEINo]                       VARCHAR (100)  NULL,
    [OSType]                       VARCHAR (100)  NULL,
    [LastLoginDt]                  DATETIME       NULL,
    [IsVehicleSpecific]            BIT            NULL,
    [LastWebLogInDatetime]         DATETIME       NULL,
    [RefreshToken]                 NVARCHAR (MAX) NULL,
    [RefreshTokenGenerateDateTime] DATETIME       NULL,
    [AccessToken]                  NVARCHAR (MAX) NULL,
    [ExpiryDatetime]               NVARCHAR (50)  NULL,
    [TokenGeneratedDatetime]       NVARCHAR (50)  NULL,
    [RefreshTokenExpiryDatetime]   NVARCHAR (50)  NULL,
    [LastAPITokenFetchDatetime]    DATETIME       NULL,
    [NextStep]                     VARCHAR (100)  NULL,
    [StepCompleted]                VARCHAR (100)  NULL,
    [UserLogo]                     NVARCHAR (500) NULL,
    CONSTRAINT [PK_MST_User] PRIMARY KEY CLUSTERED ([PK_UserId] ASC) WITH (FILLFACTOR = 90)
);

