CREATE TABLE [dbo].[MST_Account] (
    [PK_AccountId]           BIGINT         IDENTITY (1, 1) NOT NULL,
    [AccountName]            NVARCHAR (150) NULL,
    [FK_CategoryId]          BIGINT         NULL,
    [FK_CompanyId]           BIGINT         NULL,
    [FK_ResellerId]          BIGINT         NULL,
    [FK_AffiliateId]         BIGINT         NULL,
    [ParentAccountId]        BIGINT         NULL,
    [AccountAddress]         NVARCHAR (500) NULL,
    [ZipCode]                NVARCHAR (30)  NULL,
    [FK_CountryId]           BIGINT         NULL,
    [FK_StateId]             BIGINT         NULL,
    [FK_CityId]              BIGINT         NULL,
    [BillingAddress]         NVARCHAR (500) NULL,
    [ContactPerson]          NVARCHAR (150) NULL,
    [MobileNo]               NVARCHAR (20)  NULL,
    [AlternateMobileNo]      NVARCHAR (30)  NULL,
    [EmailId]                NVARCHAR (100) NULL,
    [AlternateEmailId]       NVARCHAR (100) NULL,
    [AccountLogo]            NVARCHAR (MAX) NULL,
    [AccountRegistrationNo]  NVARCHAR (50)  NULL,
    [IsActive]               BIT            NULL,
    [IsDeleted]              BIT            NULL,
    [CreatedBy]              BIGINT         NULL,
    [CreatedDateTime]        DATETIME       NULL,
    [UpdatedBy]              BIGINT         NULL,
    [UpdatedDateTime]        DATETIME       NULL,
    [DeletedBy]              BIGINT         NULL,
    [DeletedDateTime]        DATETIME       NULL,
    [ZipCode_Billing]        NVARCHAR (6)   NULL,
    [FK_CountryId_Billing]   BIGINT         NULL,
    [FK_StateId_Billing]     BIGINT         NULL,
    [FK_CityId_Billing]      BIGINT         NULL,
    [UserLimit]              INT            NULL,
    [FK_UserId]              BIGINT         NULL,
    [FK_CategoryId_Referrer] BIGINT         CONSTRAINT [DF__MST_Accou__FK_Ca__03F0984C] DEFAULT ('0') NULL,
    [FK_AccountId_Referrer]  BIGINT         CONSTRAINT [DF__MST_Accou__FK_Ac__04E4BC85] DEFAULT ('0') NULL,
    [ShareVia]               VARCHAR (50)   NULL,
    [NextStep]               VARCHAR (100)  NULL,
    [StepCompleted]          VARCHAR (100)  NULL,
    CONSTRAINT [PK__MST_A__FEE2E2D6BBA5160B] PRIMARY KEY CLUSTERED ([PK_AccountId] ASC) WITH (FILLFACTOR = 90)
);

